# service-redis
apiVersion: v1
kind: Service
metadata:
  name: service-user-data
spec:
  selector:
    app: user-data-pod
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
--- # redis-dep
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-dep
  labels:
    app: user-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-data-pod
  template:
    metadata:
      labels:
        app: user-data-pod
    spec:
      containers: #redis-cont
      - name: user-data-cont
        image: alaahajri/redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1500Mi"
            cpu: "1"
