apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort   
  ports:  # The name field is required when a service has more than one port.
  - port: 15672
    targetPort: 15672
    nodePort: 30000     # Added nodePort
    protocol: TCP
    name: management 
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30001     # Added nodePort
    protocol: TCP
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: alaahajri/rabbitmq:3-management
        ports:
        - containerPort: 15672
        - containerPort: 5672   
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"   