--- # rabbitmq-service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: web
spec:
  type: ClusterIP   
  ports:  # The name field is required when a service has more than one port.
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management 
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  selector:
    app: rabbitmq-pod
--- # rabbitmq-dep
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dep
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-pod
  template:
    metadata:
      labels:
        app: rabbitmq-pod
    spec:
      containers:
      - name: rabbitmq-cont
        image: alaahajri/rabbitmq:3-management
        ports:
        - containerPort: 15672
        - containerPort: 5672   
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1500Mi"
            cpu: "1"
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          - name: RABBITMQ_DEFAULT_PASS
            value: guest  
#         volumeMounts:
#         - name: rabbitmq-data
#           mountPath: /_data
#         - name: rabbitmq
#           mountPath: /var/lib/rabbitmq
#       volumes:
#       - name: rabbitmq-data
#         persistentVolumeClaim:
#           claimName: rabbitmq-volume-claim
#       - name: rabbitmq
#         persistentVolumeClaim:
#           claimName: rabbitmq-volume-claim          
#       restartPolicy: Always
# --- #volume
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: rabbitmq-volume-claim
#   namespace: web
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

        # readinessProbe: # probe to know when RMQ is ready to accept traffic
        #   exec:
        #     # This is just an example. There is no "one true health check" but rather
        #     # several rabbitmq-diagnostics commands that can be combined to form increasingly comprehensive
        #     # and intrusive health checks.
        #     # Learn more at https://www.rabbitmq.com/monitoring.html#health-checks.
        #     #
        #     # Stage 1 check:
        #     command: ["rabbitmq-diagnostics", "ping"]
        #   initialDelaySeconds: 20
        #   periodSeconds: 60
        #   timeoutSeconds: 10      

