--- # web service
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  # namespace: nginx-ingress
spec:
  # type: ClusterIP
  type: ClusterIP 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web-pod
--- # service-applicants-api
apiVersion: v1
kind: Service
metadata:
  name: service-api-applicants
  namespace: web
spec:
  selector:
    app: api-applicants-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
--- #service-api-identity
apiVersion: v1
kind: Service
metadata:
  name: service-api-identity
  namespace: web
spec:
  selector:
    app: api-identity-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
--- # service-api-jobs 
apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs   
  namespace: web   
spec:
  selector:
    app: api-jobs-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
--- # mssql-service
apiVersion: v1
kind: Service
metadata:
  name: service-mssql-linux
  namespace: web
spec:
  selector:
    app: mssql-linux-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
--- # rabbitmq-service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: web
  # namespace: nginx-ingress
spec:
  type: ClusterIP   
  ports:  # The name field is required when a service has more than one port.
  - port: 15672
    targetPort: 15672
    # nodePort: 30000    
    protocol: TCP
    name: management 
  - port: 5672
    targetPort: 5672
    # nodePort: 30001    
    protocol: TCP
    name: amqp
  selector:
    app: rabbitmq-pod
--- # service-redis
apiVersion: v1
kind: Service
metadata:
  name: service-user-data
  namespace: web
spec:
  selector:
    app: user-data-pod
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
