apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: web
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: my-prometheus
  namespace: web
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: my-app
  resources:
    requests:
      memory: "400Mi"
  enableAdminAPI: true
---
apiVersion: v1
kind: Service
metadata:
  name: my-prometheus
  namespace: web
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http

