apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: web
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web
type: Opaque
data:
  ConnectionString-applicants: U2VydmVyPXNlcnZpY2UtbXNzcWwtbGludXgud2ViO1VzZXI9c2E7UGFzc3dvcmQ9UGFzc0B3b3JkO0RhdGFiYXNlPWRvdG5ldGdpZ3MuYXBwbGljYW50czs=
  ConnectionString-jobs: U2VydmVyPXNlcnZpY2UtbXNzcWwtbGludXgud2ViO1VzZXI9c2E7UGFzc3dvcmQ9UGFzc0B3b3JkO0RhdGFiYXNlPWRvdG5ldGdpZ3Muam9iczs=

