apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: web
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
#   namespace: web
# type: Opaque
# data:
#   connectionStringApplicants: IlNlcnZlcj1tc3NxbC1saW51eC1zZXJ2aWNlLndlYjtVc2VyPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtEYXRhYmFzZT1kb3RuZXRnaWdzLmFwcGxpY2FudHM7Ig==
#   connectionStringJobs: IlNlcnZlcj1tc3NxbC1saW51eC1zZXJ2aWNlLndlYjtVc2VyPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtEYXRhYmFzZT1kb3RuZXRnaWdzLmpvYnM7Ig==

# Server=mssql-linux-service.web;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
# Server=mssql-linux-service.web;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;

# "Server=mssql-linux-service.web;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
# "Server=mssql-linux-service.web;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;"