--- # mssql-service
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.mssql}}
  name: {{.nameSer }} 
  namespace: {{.namespace }} 
spec:
  selector:
    app: {{.namePod }}
  ports:
    - protocol: {{.protocol }} 
      port: {{.port }} 
      targetPort: {{.port }} 
  type: {{.type }} 
  {{- end}} 
--- # mssql-dep
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.mssql}}
  name: {{.nameDep }} 
  namespace: {{.namespace }} 
spec:
  replicas: {{.replicas }} 
  selector:
    matchLabels:
      app: {{.namePod }} 
  template:
    metadata:
      labels:
        app: {{.namePod }} 
    spec:
      containers:
      - name: {{.nameCon }} 
        image: {{.imageUR }} 
        ports:
        - containerPort: {{.port }} 

        {{- if.useRessouceReqLim }}
        resources:
          requests:
            cpu: {{.reqCpu }}
            memory: {{.reqMem }}
          limits:
            cpu: {{.limCpu }}
            memory: {{.limMem }} 
        {{- end }}             

        volumeMounts:
        - name: {{.volumeName }} 
          mountPath: {{.mountPath }}
      volumes:
      - name: {{.volumeName }}
        persistentVolumeClaim:
          claimName: {{.claimName }}
      restartPolicy: {{.restartPolicy }}
  {{- end}}       
--- #volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .Values.mssql}}
  name: {{.claimName }} 
  namespace: {{.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.storage }}
  {{- end}}       